#!/bin/bash

R='0.5'
G='1.2'
B='0.5'

set_gamma() {
    for display in $(xrandr | grep ' connected' | sed 's/\s.*$//'); do
        xrandr --output "$display" --gamma "$1" || echo "$display error"
    done
}

if [[ "$1" ]]; then
    set_gamma '1:1:1'
else
    set_gamma "$R:$G:$B"
fi
